/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DetailRouteImport } from './routes/detail'
import { Route as MyRouteRouteImport } from './routes/my/route'
import { Route as WriteRouteImport } from './routes/write'
import { Route as MyIndexRouteImport } from './routes/my/index'
import { Route as MyEditRouteImport } from './routes/my/edit'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as RegisterEmailRouteImport } from './routes/register/email'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailRoute = DetailRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRouteRoute = MyRouteRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const MyIndexRoute = MyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyRouteRoute,
} as any)
const MyEditRoute = MyEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MyRouteRoute,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterEmailRoute = RegisterEmailRouteImport.update({
  id: '/register/email',
  path: '/register/email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my': typeof MyRouteRouteWithChildren
  '/detail': typeof DetailRoute
  '/write': typeof WriteRoute
  '/my/edit': typeof MyEditRoute
  '/register/email': typeof RegisterEmailRoute
  '/my/': typeof MyIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/detail': typeof DetailRoute
  '/write': typeof WriteRoute
  '/my/edit': typeof MyEditRoute
  '/register/email': typeof RegisterEmailRoute
  '/my': typeof MyIndexRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my': typeof MyRouteRouteWithChildren
  '/detail': typeof DetailRoute
  '/write': typeof WriteRoute
  '/my/edit': typeof MyEditRoute
  '/register/email': typeof RegisterEmailRoute
  '/my/': typeof MyIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my'
    | '/detail'
    | '/write'
    | '/my/edit'
    | '/register/email'
    | '/my/'
    | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/detail'
    | '/write'
    | '/my/edit'
    | '/register/email'
    | '/my'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/my'
    | '/detail'
    | '/write'
    | '/my/edit'
    | '/register/email'
    | '/my/'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyRouteRoute: typeof MyRouteRouteWithChildren
  DetailRoute: typeof DetailRoute
  WriteRoute: typeof WriteRoute
  RegisterEmailRoute: typeof RegisterEmailRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail': {
      id: '/detail'
      path: '/detail'
      fullPath: '/detail'
      preLoaderRoute: typeof DetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/': {
      id: '/my/'
      path: '/'
      fullPath: '/my/'
      preLoaderRoute: typeof MyIndexRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/my/edit': {
      id: '/my/edit'
      path: '/edit'
      fullPath: '/my/edit'
      preLoaderRoute: typeof MyEditRouteImport
      parentRoute: typeof MyRouteRoute
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/email': {
      id: '/register/email'
      path: '/register/email'
      fullPath: '/register/email'
      preLoaderRoute: typeof RegisterEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MyRouteRouteChildren {
  MyEditRoute: typeof MyEditRoute
  MyIndexRoute: typeof MyIndexRoute
}

const MyRouteRouteChildren: MyRouteRouteChildren = {
  MyEditRoute: MyEditRoute,
  MyIndexRoute: MyIndexRoute,
}

const MyRouteRouteWithChildren =
  MyRouteRoute._addFileChildren(MyRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyRouteRoute: MyRouteRouteWithChildren,
  DetailRoute: DetailRoute,
  WriteRoute: WriteRoute,
  RegisterEmailRoute: RegisterEmailRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
